### ISSUE TITLE
Where are the given and received reaction after the last update (member profile)?

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#31] opened 2018-01-02 15:24 UTC
There was a box with all reaction given and received in a member profile, now it is gone :( Why? I can see settings for that but no output, do I have to add them manually? This was a really cool feature. Thank you

https://github.com/WhiteNeo/post_rate/issues/11

**Comment by WhiteNeo** [comment] 2018-01-02 15:33
Do you have {$memprofile['dnt_prt']}

in your member profile template ?

That var gets the content inside dnt_prt_stats on Post Rate templates.

There you have the vars and more, but it have to be showed :) maybe it is another bug in this new version, but at this point all that i have do is run Deactivate and Activate, this retrieve database anyway and only loads css, templates and more, you know all stuff for this plugin.

Anyway let me know because is very important to get this working fine in this version.

Thanks for your time.

**Comment by Eldenroot** [comment] 2018-01-02 17:21
Yes, it is there but it is not working. My member_profile template:
![image](https://user-images.githubusercontent.com/778890/34492888-bfbcc46a-efe9-11e7-9501-ead8ade2959f.png)

My member profile page output:
![image](https://user-images.githubusercontent.com/778890/34492908-ccb0883c-efe9-11e7-9a39-e77089d45805.png)

**Comment by Eldenroot** [comment] 2018-01-02 17:27
OK, I uploaded your latest version from GitHub with your latest changes and it works again, thank you!

One more thing - I dont get it why you wanna show only top 5 reactions? We have 6 reactions in total, so maybe you should show all six and change the language a little bit :)

![image](https://user-images.githubusercontent.com/778890/34493085-998f621a-efea-11e7-9fed-8f29a1421c31.png)

**Comment by Eldenroot** [comment] 2018-01-02 17:34
You can use something like this:
"Summary of all reactions received" and "Summary of all reactions given"

+ can you use same order of icons as in "Rate button"? So first from left to right "Like" -> "Love" -> "Wow" -> "Smile" -> "Cry" -> "Angry"

**Comment by WhiteNeo** [comment] 2018-01-02 20:20
It counts the most used emojis, and it is ordered + to - and it is marked as 5 because in near future or due users maybe can be more than 6 but i dunno yet maybe i will let that in best 3 or best reactions used, but this is in beta :)

**Comment by Eldenroot** [comment] 2018-01-03 20:21
@WhiteNeo - **please leave this plugin only for 6 reactions (Facebook style) and DO NOT add this option for users (adding more reaction icons)... this will be a must wanted plugin for MyBB when will be released as a stable version with all bugs fixed and polished design UI. I am here and open to help you with improving and catching bugs.**

In my opinion - show all 6 reactions in that box and DO NOT limit to 5... if do you wanna this just add a separate settings for this.

**Comment by WhiteNeo** [comment] 2018-01-04 00:42
Ok i'll do that and will modify either lang typos.

**Comment by Eldenroot** [comment] 2018-01-05 14:53
@WhiteNeo - so, now the reactions are ordered by quantity descending?

**Comment by WhiteNeo** [comment] 2018-01-05 14:56
Nope now is taken in order by id as posts and threalist.

This will work that way and an ordered list must shown with counters only.

It have to add some other class to remove pointer this parts, but anyway current version works better.

And your host allways shows the same error again and again i was tryed due your message into mybb forums and nope, i can not login 0 times i have tryed so i put this on my forums to work that way in new bugs and more it is more easy for me this way, test there and let me know because i am thinking the problem is with your host and domain is configured wrong and allways sent that same error.

**Comment by Eldenroot** [comment] 2018-01-05 14:58
OK, so send me the URL - I will test it in your board

**Closed as completed** 2018-01-05 14:59 UTC
