### ISSUE TITLE
Regression - not working setting - threadlist - show only from fist post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#48] opened 2018-01-07 12:41 UTC
This setting is not working
![image](https://user-images.githubusercontent.com/778890/34649472-4cd5918c-f3b0-11e7-9fe6-0fd7a44da74e.png)

It shows all rates, not just from the first post (it was working fine before).

**Comment by WhiteNeo** [comment] 2018-01-07 13:02
Ok i will review it, because this is one of the new addons and i will make it works perfect, thanks...

**Comment by WhiteNeo** [comment] 2018-01-07 13:46
Have you run recount tool ?

If you have preview data then this will load all new changes in the list, if do not (clean installation) Only add new emojis and have to work i am testing this right now but it works fine, only if you have old data you have to run recount tool once. Then all have data must be retrieveved and i have added more changes due last issues.

**Comment by WhiteNeo** [comment] 2018-01-07 14:23
I have added as bug label but i can not reproduce error you have mentioned.

![list](https://user-images.githubusercontent.com/5620232/34650270-cf101e56-f383-11e7-9abf-580b7cade272.png)

This is an image with threadlist only first post, if i have all thread besides that then the counter is 43 besides 23, as you can see is the first post value, verify please this to continue another parts of plugin, anyway i am testing this part right now.

**Comment by WhiteNeo** [comment] 2018-01-07 14:32
And i have added a video of the actual mod here:

https://mega.nz/#!jlhTnLyb!crZs2ED87lHjF4FSQQy1nT20zAJLgHbDQ9Wm7UiCzEg

This is with the new addons, and all the issues fixed, actual ones only i mean.

**Comment by Eldenroot** [comment] 2018-01-07 17:11
@WhiteNeo - it is not working for me... plugin was uninstalled (dropped DB tables), replaced old files with new ones and activated again.

Still same issue, when the first post is not rated and you rate for example the 3rd one, you can see this emoji in threadlist.

feel free to test it again on my test board, same pw and username... I just uploaded your latest version from GitHub and recounted 
  

P.S. It was fine 2 days ago with your 1.6.2 release

**Comment by Eldenroot** [comment] 2018-01-07 17:13
Here is the rated post (2nd post in thread); the first one has no ratings.
![image](https://user-images.githubusercontent.com/778890/34651851-672e2afa-f3d6-11e7-949c-02bbb695d0a2.png)
Here is a threadlist - emoji from the second post is displayed (even it was disabled in ACP setting)
![image](https://user-images.githubusercontent.com/778890/34651856-81bc9168-f3d6-11e7-97f9-3942377675c3.png)

 And here is my settings:
![image](https://user-images.githubusercontent.com/778890/34651862-b44e740c-f3d6-11e7-84e4-b691976d75b6.png)

**Comment by WhiteNeo** [comment] 2018-01-07 17:16
I have removed all my pms from mybb site, and i do not remember your host due it causes many troubles to login for me, but i will review this in my localhost is more easy and quick for me only knowing how to reproduce error to make a quick fix for it.

Thanks for all your time now i think i can reproduce error and can wirte a fix for this, but you have told me do not work i was think about there are 0 results in there, but in the video provided i use many emojis in many threads but already have some data inside first post i think this issue is related to non rated ones but the next posts. I will give a try right now.

**Comment by WhiteNeo** [comment] 2018-01-07 17:35
Ok you were right but anyway recount task must fix that error, anyway is fixed now, try it and let me know.

**Comment by Eldenroot** [comment] 2018-01-07 18:42
@WhiteNeo - please check my comment here: https://github.com/WhiteNeo/post_rate/commit/b74f622cadb528bf3f053f67958c53a614591926

**Comment by Eldenroot** [comment] 2018-01-07 18:47
OK, should be fine now... anyway there is another issue probably related to this one #47 

![image](https://user-images.githubusercontent.com/778890/34652814-8bea01b8-f3e3-11e7-9e87-bf4289f5a998.png)

**Comment by WhiteNeo** [comment] 2018-01-07 18:56
I have fixed js well somehow i had replaced again :(

Now have to work. I have added some style changes but now i have to review containers. Because all styles are different. Well this is the next on my eye.

Thanks, all other stuff shoul work but only this is the missing one :)

I have fixed some other errors in style customizations anyway.

And i use other postbit, so now i will see both and work on that part.

**Comment by Eldenroot** [comment] 2018-01-07 19:22
OK, I have to reopen this issue, it is still bugged. I sent you PM and username over PM in MyBB community board.

**Comment by Eldenroot** [comment] 2018-01-07 20:03
@WhiteNeo - found the issue - it is fine until you run recount post rates... after that it is bugged

**Comment by WhiteNeo** [comment] 2018-01-07 20:11
Ok the other error was ;  additions i have removed due mimified css rules ;)

But recount feature must be the problem, i will review that but only the bug is on recount feature due new addons i have not reviewed that part yet :o

**Comment by WhiteNeo** [comment] 2018-01-07 20:22
Ok do not remove nothing due all data is on database tables, on posts and thread information in loaded into new db field to not consume queries, so recount tool is the problem now, verify it only upload plugin file, run recount tool and let me know, i think is that part with option for all posts only with only first post must run fine. Anyway i have modified that part, so try it and let me know :)

**Closed as completed** 2018-01-08 09:26 UTC
Labels: bug

**Comment by Eldenroot** [comment] 2018-01-08 19:57
Works fine, thank you!
